package view;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;
import javax.swing.JPanel;

public class Jeu extends JPanel{
	

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	String LaMap = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDEDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDRRRDDDDDDDDRRRDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXDDDDDDDDDDDDDDDDDDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
	char Map1D[] = LaMap.toCharArray();
    char Map2D[][] = new char [60][40];
	
	public void paintComponent(Graphics g){
		
		Image wall = null;
		Image diamond = null;
		Image rock = null;
		Image dirt = null;
		Image exit = null;
		Image back = null;
		
		try {
			wall = ImageIO.read(new File("Sprites/Blocks/Wall.png"));
			diamond = ImageIO.read(new File("Sprites/Blocks/Diamond.png"));
			rock = ImageIO.read(new File("Sprites/Blocks/Rock.png"));
			dirt = ImageIO.read(new File("Sprites/Blocks/Dirt.png"));
			exit = ImageIO.read(new File("Sprites/Blocks/Exit_close.png"));
			back = ImageIO.read(new File("Sprites/Blocks/Background.png"));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		for(int i = 0; i < 60; i++)
        {        		
        	for(int j = 0; j <40; j++)
        	{   
        		Map2D[i][j] = Map1D[(j*60)+i];
        	}
        }
		for(int i = 0; i < 60; i++)
        {        		
        	for(int j = 0; j <40; j++)
        	{   
        		switch(Map2D[i][j])
        		{
        		case 'X' :
        			g.drawImage(wall, i*25, j*25, 25, 25, this);  
        			System.out.print("X");
        			break;
        		case 'D' :
        			g.drawImage(dirt, i*25, j*25, 25, 25, this);  
        			System.out.print("D");
        			break;
        		case 'R' :
        			g.drawImage(rock, i*25, j*25, 25, 25, this);  
        			System.out.print("R");
        			break;
        		default :
        			System.out.print(" ");
        		}
        	}
        	System.out.println("");
        }
		
	}
	
	public Jeu(FenetreJeu fen) {
		super();
	}
	public void close()
	{
		this.setVisible(false);
			
	}
		
}
